### PR TITLE
set inputs and outputs, set interrupts and ISRs, having issues with t…

### PR DESCRIPTION
**Pull request by ljordan51**
…esting, difficult to describe

### CODE REVIEW

**Comment by ljordan51** [comment]
added commit to fix one bug, still troubleshooting final bug

**Comment by ljordan51** [comment]
board had floating connection, now need to add CAN communication

**Comment by aehoppe** [comment]
Added shutdown CAN communication @rileychapman

**Review by aehoppe — APPROVED** [review]
Seems fine, merging.

**Pull request merged**
